version: '3.3'

networks:
  backend:
    ipam:
      config:
        - subnet: 172.18.1.0/24
        
volumes:
  mongodbdata:
    driver: local

services:
  flaskapi:
    build:
      context: flaskAPI
      dockerfile: ./development.Dockerfile
    container_name: flaskapi
    environment:
      FLASK_APP: run.py
      FLASK_ENV: development
      FLASK_DEBUG: 1
      MONGODB_CONNECTION_STRING: mongodb+srv://bet-royale-leader:ECWObn4uW1Hvfj1U@bet-royale-bd.k5r0uf0.mongodb.net/
      PAYPAL_API_URL: https://api-m.sandbox.paypal.com
      PAYPAL_CLIENT_ID: AYcoOZajPBns1FI6WbHvgIGzsAJx1AWnY6rOwrvtiBoGlc4KrUeIJhtSlZI5CRjdKVmM3KrV7jt5rf3C
      PAYPAL_SECRET: EKN-6LShkjDKI5nVBMGBFR7F-t6aiz6zSw8Ns8bgtjuixXmENACz3Z1EeronchlytYe69P4oYWZNwuz4
      ODDS_API_KEY: 87c963d43e0c21a33f7d029816a95f77
      SECRET_KEY: VitAo;wH7noT2y2c!}yN'?o=X1|:[T]l!RS3;<s_?rW^a-S>+zQ9fItgn>T5{lguuid.uu
      CLIENT_DOMAIN: http://localhost:3000
      DOMAIN: http://localhost:8000
      GMAIL_USER: betroyale67@gmail.com
      GMAIL_PASSWORD: plnstkgnfanqcyww
      PORT: 8000
    networks:
      backend:
        ipv4_address: 172.18.1.4
    ports:
      - 8000:8000
      - 5678:5678
    entrypoint: [ "python", "-m", "debugpy", "--listen", "0.0.0.0:5678", "-m", "run",  "--wait-for-client", "--multiprocess", "-m", "flask", "run", "-h", "0.0.0.0", "-p", "8000" ]
    expose:
      - 8000
    volumes:
      - ./flaskAPI:/flask

  mongodb:
    image: mongo
    container_name: 'mongodb'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: golf123
      MONGO_INITDB_DATABASE: flaskdb
      MONGODB_DATA_DIR: /data/db
      MONGODB_LOG_DIR: /dev/null
    networks:
      backend:
        ipv4_address: 172.18.1.2
    volumes:
      - mongodbdata:/data/db
    ports: 
      - 27017:27017